# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160324_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
