# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='cuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
