# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0002_auto_20160315_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
