# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0003_auto_20160322_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
